apiVersion: v1
kind: Pod
metadata:
  name: telebot-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: telebot-container
      image: tch1001/abcdefg:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: telebot-secret
              key: API_KEY
              optional: false
      #args: ["migrate","sql", "-e", "--yes"]
      #command: ['tail', '-f', '/dev/null']
      command: ['python', 'messenger.py']
