apiVersion: v1
kind: Pod
metadata:
  name: wayyan-discord-bot-pod
spec:
  restartPolicy: Never
  containers:
    - name: wayyan-discord-bot-container
      image: tch1001/sgmaff:v3
      imagePullPolicy: "IfNotPresent"
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: wayyan-discord-bot-secret
              key: API_KEY
              optional: false
      #args: ["migrate","sql", "-e", "--yes"]
      #command: ['tail', '-f', '/dev/null']
      command: ['python', 'bot.py']
